version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ekklesia3d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ekklesia3d2025
      MYSQL_DATABASE: ekklesia3d
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Ekklesia3d2025

volumes:
  db_data:
